---
- name: Upgrade all packages using Debian 'apt'
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist

- name: Restart needed libraries/services
  become: true
  ansible.builtin.command: needrestart -ra -freadline
  ignore_errors: true
  failed_when: false
  changed_when: false

- name: Trigger reboot on new kernel installation
  become: true
  ansible.builtin.command: needrestart -p -freadline
  register: restart_needed
  ignore_errors: true
  failed_when: false
  changed_when: restart_needed.rc != 0
  notify:
    - Reboot Host
