---
# tasks file for host_update
- name: Upgrade all packages (OS / distro dependent)
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution | lower }}.yml'
        - '{{ ansible_os_family | lower }}.yml'
      skip: true
