---
- name: Upgrade all packages
  become: true
  ansible.builtin.dnf:
    name: "*"
    update_cache: true
    state: latest

- name: Remove obsolete packages
  become: true
  ansible.builtin.dnf:
    autoremove: true

- name: Check to see if reboot required after update
  become: true
  ansible.builtin.command: needs-restarting -r
  register: restart_needed
  ignore_errors: true
  failed_when: false
  changed_when: restart_needed.rc != 0
  notify:
    - Reboot Host
