---
- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist

- name: Restart needed libraries/services
  become: true
  ansible.builtin.command:
    cmd: needrestart -f noninteractive -ra
  changed_when: false

- name: Check to see if reboot required after update
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: st

- name: Reboot if required
  become: true
  ansible.builtin.reboot:
  when: st.stat.exists == True
