---
# tasks file for Debian common_packages
- name: Install common packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "{{ common_packages }}"
    state: present
