---
# tasks file for Redhat common_packages
- name: Install common packages family via Redhat 'dnf'
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name: "{{ common_packages }}"
    state: present
