---
- name: Get current value of restart on power failure
  command: "systemsetup -getrestartpowerfailure"
  register: result
  changed_when: False

- name: Enable restart on power failure if disabled
  command: "systemsetup -setrestartpowerfailure on"
  when: "': On' not in result.stdout"

- name: Get current value of restart on system freeze
  command: "systemsetup -getrestartfreeze"
  register: result
  changed_when: False

- name: Enable restart on system freeze if disabled
  command: "systemsetup -setrestartfreeze on"
  when: "': On' not in result.stdout"
