galaxy_info:
  author: Scott Burns
  description: Update hosts
  company: Cipher23 LLC

  license: MIT

  min_ansible_version: "2.1"

  platforms:

    - name: Debian
      versions:
        - buster
        - bullseye

    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy

  galaxy_tags:
    - system

dependencies: []
