---
# handlers file for ansible-role-unbound
- name: Restart Unbound
  become: true
  ansible.builtin.service:
    name: unbound
    state: restarted
  tags:
    - configure_service

# reload the systemd daemon
- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
